# Generated by Django 4.0.4 on 2022-10-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='dishes/', verbose_name='Изображени'),
        ),
    ]
